name: Build macOS .app

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install py2app google-auth google-auth-oauthlib requests

      - name: Build .app
        run: |
          source venv/bin/activate
          python setup.py py2app

      - name: Upload dist/ as artifact
        uses: actions/upload-artifact@4
        with:
          name: RAW-Finder-app
          path: dist/